"""Shared helpers and goldens for the walk-shapes test family, not collected.

The byte-exact _WALK_LINES and _TREES goldens plus _plan and _branch_walks.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from tests._helpers import _copy_lab, _run_cli_in, fixtures_root

# _copy_lab and _run_cli_in live in tests._helpers and are re-exported here
# beside the goldens for the test_walk_shapes* suites.
__all__ = [
    "_TREES",
    "_WALK_LINES",
    "_branch_walks",
    "_copy_lab",
    "_plan",
    "_run_cli_in",
]

if TYPE_CHECKING:
    from daedalus.core.walks import WalkPlan

_FIXTURE_LABS = fixtures_root() / "labs"

# The byte-exact walk-line block per shape (Full and numbered Walks lines),
# verified against core/walks._render_lines on the authored fixture.
_WALK_LINES: dict[str, tuple[str, ...]] = {
    "chain_plain": (
        "Full:  1-2-3",
        "Walks: 1",
        "  walk_1: 1-2-3",
    ),
    "wide4_join": (
        "Full:  1-(2,3,4,5)-6",
        "Walks: 4",
        "  walk_1: 1-2-(6)",
        "  walk_2: 1-3-(6)",
        "  walk_3: 1-4-(6)",
        "  walk_4: 1-5-(6)",
    ),
    "wide5_join": (
        "Full:  1-(2,3,4,5,6)-7",
        "Walks: 5",
        "  walk_1: 1-2-(7)",
        "  walk_2: 1-3-(7)",
        "  walk_3: 1-4-(7)",
        "  walk_4: 1-5-(7)",
        "  walk_5: 1-6-(7)",
    ),
    "asym_join": (
        "Full:  1-(2,3-4-5)-6",
        "Walks: 2",
        "  walk_1: 1-2-(6)",
        "  walk_2: 1-3-4-5-(6)",
    ),
    # Outer walk_1 (w2) includes its descendant inner steps 4-5 and marks only
    # its own closer (7); inner walks mark (6).
    "nested_join": (
        "Full:  1-(2-(4,5)-6,3)-7",
        "Walks: 4",
        "  walk_1: 1-2-4-5-6-(7)",
        "  walk_2: 1-3-(7)",
        "  walk_3: 1-2-4-(6)-7",
        "  walk_4: 1-2-5-(6)-7",
    ),
    # Four branch walks (src's two plus mid's two); the walk count adds. The first
    # diamond's group renders as the merged backbone node 4 on the second diamond's
    # lines.
    "series_diamonds": (
        "Full:  1-(2,3)-4-5-(6,7)-8",
        "Walks: 4",
        "  walk_1: 1-2-(4)-5-8",
        "  walk_2: 1-3-(4)-5-8",
        "  walk_3: 1-4-5-6-(8)",
        "  walk_4: 1-4-5-7-(8)",
    ),
    "repeat_then_collect": (
        "Full:  1-(2-4,3-4)-5",
        "Walks: 2",
        "  walk_1: 1-2-4-(5)",
        "  walk_2: 1-3-4-(5)",
    ),
    # Both branches are terminal (uncollected), so no (N) marker. The repeated sink d
    # (module 4) renders as a per-walk member inside each group branch, consistent
    # with the repeat_then_collect Full line.
    "diamond_repeat": (
        "Full:  1-(2-4,3-4)",
        "Walks: 2",
        "  walk_1: 1-2-4",
        "  walk_2: 1-3-4",
    ),
    # Wide brancher, repeated terminal sink (one native instance per walk).
    # Uncollected -> no marker; the repeated sink renders per-member.
    "wide4_repeat": (
        "Full:  1-(2-6,3-6,4-6,5-6)",
        "Walks: 4",
        "  walk_1: 1-2-6",
        "  walk_2: 1-3-6",
        "  walk_3: 1-4-6",
        "  walk_4: 1-5-6",
    ),
    "wide5_repeat": (
        "Full:  1-(2-7,3-7,4-7,5-7,6-7)",
        "Walks: 5",
        "  walk_1: 1-2-7",
        "  walk_2: 1-3-7",
        "  walk_3: 1-4-7",
        "  walk_4: 1-5-7",
        "  walk_5: 1-6-7",
    ),
    # Inner group collected at 6 (marked on the inner walks), outer group not.
    # walk_1, the outer deep branch, includes its inner steps 4-5-6 and carries no
    # marker since its own group has no closer, as in nested_join without top_join.
    "mixed_collect": (
        "Full:  1-(2-(4,5)-6,3)",
        "Walks: 4",
        "  walk_1: 1-2-4-5-6",
        "  walk_2: 1-3",
        "  walk_3: 1-2-4-(6)",
        "  walk_4: 1-2-5-(6)",
    ),
    # The exoplanet shape at M=1 (emitter, brancher x4, three sibling walk_collectors,
    # flight collector, sink). [8,9,10] is three concurrent collectors over the same
    # branch group; collectors mint no walks.
    "sibling_collectors": (
        "Full:  1-2-3-(4,5,6,7)-[8,9,10]-11-12",
        "Walks: 4",
        "  walk_1: 1-2-3-4-(8)-(9)-(10)-11-12",
        "  walk_2: 1-2-3-5-(8)-(9)-(10)-11-12",
        "  walk_3: 1-2-3-6-(8)-(9)-(10)-11-12",
        "  walk_4: 1-2-3-7-(8)-(9)-(10)-11-12",
    ),
}

# The sorted relative dir paths per shape under flows/<id>/, with the <id> segment
# and every dae-* entry stripped, verified against dae lab run. Flightless
# throughout, so walks/ nests directly under the flow root.
_TREES: dict[str, tuple[str, ...]] = {
    "asym_join": (
        "final",
        "walks",
        "walks/walk_1",
        "walks/walk_1/01_src",
        "walks/walk_1/02_quick",
        "walks/walk_1/03_join",
        "walks/walk_2",
        "walks/walk_2/01_src",
        "walks/walk_2/02_slow_a",
        "walks/walk_2/03_slow_b",
        "walks/walk_2/04_slow_c",
        "walks/walk_2/05_join",
    ),
    "chain_plain": (
        "final",
        "walks",
        "walks/walk_1",
        "walks/walk_1/01_step_a",
        "walks/walk_1/02_step_b",
        "walks/walk_1/03_step_c",
    ),
    "diamond_repeat": (
        "walks",
        "walks/walk_1",
        "walks/walk_1/01_seed",
        "walks/walk_1/02_left",
        "walks/walk_1/03_d",
        "walks/walk_2",
        "walks/walk_2/01_seed",
        "walks/walk_2/02_right",
        "walks/walk_2/03_d",
    ),
    "mixed_collect": (
        "walks",
        "walks/walk_1",
        "walks/walk_1/01_src",
        "walks/walk_1/02_deep",
        "walks/walk_1/03_sub_a",
        "walks/walk_1/04_sub_join",
        "walks/walk_2",
        "walks/walk_2/01_src",
        "walks/walk_2/02_deep",
        "walks/walk_2/03_sub_b",
        "walks/walk_2/04_sub_join",
        "walks/walk_3",
        "walks/walk_3/01_src",
        "walks/walk_3/02_side",
    ),
    "nested_join": (
        "final",
        "walks",
        "walks/walk_1",
        "walks/walk_1/01_src",
        "walks/walk_1/02_mid",
        "walks/walk_1/03_sub_a",
        "walks/walk_1/04_sub_join",
        "walks/walk_1/05_top_join",
        "walks/walk_2",
        "walks/walk_2/01_src",
        "walks/walk_2/02_mid",
        "walks/walk_2/03_sub_b",
        "walks/walk_2/04_sub_join",
        "walks/walk_2/05_top_join",
        "walks/walk_3",
        "walks/walk_3/01_src",
        "walks/walk_3/02_side",
        "walks/walk_3/03_top_join",
    ),
    "repeat_then_collect": (
        "final",
        "walks",
        "walks/walk_1",
        "walks/walk_1/01_seed",
        "walks/walk_1/02_left",
        "walks/walk_1/03_d",
        "walks/walk_1/04_join",
        "walks/walk_2",
        "walks/walk_2/01_seed",
        "walks/walk_2/02_right",
        "walks/walk_2/03_d",
        "walks/walk_2/04_join",
    ),
    "series_diamonds": (
        "final",
        "walks",
        "walks/walk_1",
        "walks/walk_1/01_src",
        "walks/walk_1/02_a1",
        "walks/walk_1/03_join1",
        "walks/walk_1/04_mid",
        "walks/walk_1/05_b1",
        "walks/walk_1/06_join2",
        "walks/walk_2",
        "walks/walk_2/01_src",
        "walks/walk_2/02_a1",
        "walks/walk_2/03_join1",
        "walks/walk_2/04_mid",
        "walks/walk_2/05_b2",
        "walks/walk_2/06_join2",
        "walks/walk_3",
        "walks/walk_3/01_src",
        "walks/walk_3/02_a2",
        "walks/walk_3/03_join1",
        "walks/walk_3/04_mid",
        "walks/walk_3/05_b1",
        "walks/walk_3/06_join2",
        "walks/walk_4",
        "walks/walk_4/01_src",
        "walks/walk_4/02_a2",
        "walks/walk_4/03_join1",
        "walks/walk_4/04_mid",
        "walks/walk_4/05_b2",
        "walks/walk_4/06_join2",
    ),
    "sibling_collectors": (
        "final",
        "flights",
        "flights/flight_1",
        "flights/flight_1/final",
        "flights/flight_1/walks",
        "flights/flight_1/walks/walk_1",
        "flights/flight_1/walks/walk_1/01_emit",
        "flights/flight_1/walks/walk_1/02_prep",
        "flights/flight_1/walks/walk_1/03_split",
        "flights/flight_1/walks/walk_1/04_fit_a",
        "flights/flight_1/walks/walk_1/05_coll_a",
        "flights/flight_1/walks/walk_1/06_fcollect",
        "flights/flight_1/walks/walk_1/07_sink",
        "flights/flight_1/walks/walk_10",
        "flights/flight_1/walks/walk_10/01_emit",
        "flights/flight_1/walks/walk_10/02_prep",
        "flights/flight_1/walks/walk_10/03_split",
        "flights/flight_1/walks/walk_10/04_fit_d",
        "flights/flight_1/walks/walk_10/05_coll_a",
        "flights/flight_1/walks/walk_10/06_fcollect",
        "flights/flight_1/walks/walk_10/07_sink",
        "flights/flight_1/walks/walk_11",
        "flights/flight_1/walks/walk_11/01_emit",
        "flights/flight_1/walks/walk_11/02_prep",
        "flights/flight_1/walks/walk_11/03_split",
        "flights/flight_1/walks/walk_11/04_fit_d",
        "flights/flight_1/walks/walk_11/05_coll_b",
        "flights/flight_1/walks/walk_11/06_fcollect",
        "flights/flight_1/walks/walk_11/07_sink",
        "flights/flight_1/walks/walk_12",
        "flights/flight_1/walks/walk_12/01_emit",
        "flights/flight_1/walks/walk_12/02_prep",
        "flights/flight_1/walks/walk_12/03_split",
        "flights/flight_1/walks/walk_12/04_fit_d",
        "flights/flight_1/walks/walk_12/05_coll_c",
        "flights/flight_1/walks/walk_12/06_fcollect",
        "flights/flight_1/walks/walk_12/07_sink",
        "flights/flight_1/walks/walk_2",
        "flights/flight_1/walks/walk_2/01_emit",
        "flights/flight_1/walks/walk_2/02_prep",
        "flights/flight_1/walks/walk_2/03_split",
        "flights/flight_1/walks/walk_2/04_fit_a",
        "flights/flight_1/walks/walk_2/05_coll_b",
        "flights/flight_1/walks/walk_2/06_fcollect",
        "flights/flight_1/walks/walk_2/07_sink",
        "flights/flight_1/walks/walk_3",
        "flights/flight_1/walks/walk_3/01_emit",
        "flights/flight_1/walks/walk_3/02_prep",
        "flights/flight_1/walks/walk_3/03_split",
        "flights/flight_1/walks/walk_3/04_fit_a",
        "flights/flight_1/walks/walk_3/05_coll_c",
        "flights/flight_1/walks/walk_3/06_fcollect",
        "flights/flight_1/walks/walk_3/07_sink",
        "flights/flight_1/walks/walk_4",
        "flights/flight_1/walks/walk_4/01_emit",
        "flights/flight_1/walks/walk_4/02_prep",
        "flights/flight_1/walks/walk_4/03_split",
        "flights/flight_1/walks/walk_4/04_fit_b",
        "flights/flight_1/walks/walk_4/05_coll_a",
        "flights/flight_1/walks/walk_4/06_fcollect",
        "flights/flight_1/walks/walk_4/07_sink",
        "flights/flight_1/walks/walk_5",
        "flights/flight_1/walks/walk_5/01_emit",
        "flights/flight_1/walks/walk_5/02_prep",
        "flights/flight_1/walks/walk_5/03_split",
        "flights/flight_1/walks/walk_5/04_fit_b",
        "flights/flight_1/walks/walk_5/05_coll_b",
        "flights/flight_1/walks/walk_5/06_fcollect",
        "flights/flight_1/walks/walk_5/07_sink",
        "flights/flight_1/walks/walk_6",
        "flights/flight_1/walks/walk_6/01_emit",
        "flights/flight_1/walks/walk_6/02_prep",
        "flights/flight_1/walks/walk_6/03_split",
        "flights/flight_1/walks/walk_6/04_fit_b",
        "flights/flight_1/walks/walk_6/05_coll_c",
        "flights/flight_1/walks/walk_6/06_fcollect",
        "flights/flight_1/walks/walk_6/07_sink",
        "flights/flight_1/walks/walk_7",
        "flights/flight_1/walks/walk_7/01_emit",
        "flights/flight_1/walks/walk_7/02_prep",
        "flights/flight_1/walks/walk_7/03_split",
        "flights/flight_1/walks/walk_7/04_fit_c",
        "flights/flight_1/walks/walk_7/05_coll_a",
        "flights/flight_1/walks/walk_7/06_fcollect",
        "flights/flight_1/walks/walk_7/07_sink",
        "flights/flight_1/walks/walk_8",
        "flights/flight_1/walks/walk_8/01_emit",
        "flights/flight_1/walks/walk_8/02_prep",
        "flights/flight_1/walks/walk_8/03_split",
        "flights/flight_1/walks/walk_8/04_fit_c",
        "flights/flight_1/walks/walk_8/05_coll_b",
        "flights/flight_1/walks/walk_8/06_fcollect",
        "flights/flight_1/walks/walk_8/07_sink",
        "flights/flight_1/walks/walk_9",
        "flights/flight_1/walks/walk_9/01_emit",
        "flights/flight_1/walks/walk_9/02_prep",
        "flights/flight_1/walks/walk_9/03_split",
        "flights/flight_1/walks/walk_9/04_fit_c",
        "flights/flight_1/walks/walk_9/05_coll_c",
        "flights/flight_1/walks/walk_9/06_fcollect",
        "flights/flight_1/walks/walk_9/07_sink",
    ),
    "wide4_join": (
        "final",
        "walks",
        "walks/walk_1",
        "walks/walk_1/01_src",
        "walks/walk_1/02_b_a",
        "walks/walk_1/03_join",
        "walks/walk_2",
        "walks/walk_2/01_src",
        "walks/walk_2/02_b_b",
        "walks/walk_2/03_join",
        "walks/walk_3",
        "walks/walk_3/01_src",
        "walks/walk_3/02_b_c",
        "walks/walk_3/03_join",
        "walks/walk_4",
        "walks/walk_4/01_src",
        "walks/walk_4/02_b_d",
        "walks/walk_4/03_join",
    ),
    "wide4_repeat": (
        "walks",
        "walks/walk_1",
        "walks/walk_1/01_src",
        "walks/walk_1/02_b_a",
        "walks/walk_1/03_sink",
        "walks/walk_2",
        "walks/walk_2/01_src",
        "walks/walk_2/02_b_b",
        "walks/walk_2/03_sink",
        "walks/walk_3",
        "walks/walk_3/01_src",
        "walks/walk_3/02_b_c",
        "walks/walk_3/03_sink",
        "walks/walk_4",
        "walks/walk_4/01_src",
        "walks/walk_4/02_b_d",
        "walks/walk_4/03_sink",
    ),
    "wide5_join": (
        "final",
        "walks",
        "walks/walk_1",
        "walks/walk_1/01_src",
        "walks/walk_1/02_b_a",
        "walks/walk_1/03_join",
        "walks/walk_2",
        "walks/walk_2/01_src",
        "walks/walk_2/02_b_b",
        "walks/walk_2/03_join",
        "walks/walk_3",
        "walks/walk_3/01_src",
        "walks/walk_3/02_b_c",
        "walks/walk_3/03_join",
        "walks/walk_4",
        "walks/walk_4/01_src",
        "walks/walk_4/02_b_d",
        "walks/walk_4/03_join",
        "walks/walk_5",
        "walks/walk_5/01_src",
        "walks/walk_5/02_b_e",
        "walks/walk_5/03_join",
    ),
    "wide5_repeat": (
        "walks",
        "walks/walk_1",
        "walks/walk_1/01_src",
        "walks/walk_1/02_b_a",
        "walks/walk_1/03_sink",
        "walks/walk_2",
        "walks/walk_2/01_src",
        "walks/walk_2/02_b_b",
        "walks/walk_2/03_sink",
        "walks/walk_3",
        "walks/walk_3/01_src",
        "walks/walk_3/02_b_c",
        "walks/walk_3/03_sink",
        "walks/walk_4",
        "walks/walk_4/01_src",
        "walks/walk_4/02_b_d",
        "walks/walk_4/03_sink",
        "walks/walk_5",
        "walks/walk_5/01_src",
        "walks/walk_5/02_b_e",
        "walks/walk_5/03_sink",
    ),
}


def _plan(name: str) -> WalkPlan:
    """Propagate the fixture lab and assert the result is a WalkPlan."""
    from daedalus.core import walks
    from daedalus.core.recipe import load_recipe

    lab = _FIXTURE_LABS / name
    result = walks.propagate(load_recipe(lab / "lab.yaml"), lab)
    assert isinstance(result, walks.WalkPlan), result
    return result


def _branch_walks(plan) -> list:  # noqa: ANN001, ANN202
    return [r for r in plan.walks if r.branch_module is not None]
